# This workflow will install Python dependencies, run full checks defined in `.pre-commit-config.yaml` with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: cpp-checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: install packages
      run: sudo apt update -y; sudo apt install -y build-essential make libopenblas-dev cpputest clang-format-11 clang-tidy-11 libc++-dev
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: setup pre-commit
      run: pip install .[develop]
    - name: Run checks
      run: SKIP=no-commit-to-branch,flake8,pytest,clang-tidy pre-commit run -a
